### ISSUE TITLE
Jupyter Notebook

### ISSUE THREAD

**Issue by Aayush9029** [Sentdex/NNfSiX#104]
#### Or does it fall under the category of python?

> if we can where can we add them under python folder or by making a new folder in the branch.

**Comment by GyanendroKh** [comment]
I think there is no need for Jupyter Notebook `(just my thought)`.   
This repo is more about the language not tool.   
Jupyter is just a way to run the Python code and we already have the python code.

**Comment by AnonymousPyro** [comment]
Read it [here](https://github.com/Sentdex/NNfSiX/pull/40)

**Comment by daniel-kukiela** [comment]
Yes, for the mentioned reasons we strongly do not recommend using a notebook in this case. Then it does not differ much from the python files as it'll contain the same code, just in a different form.
