### ISSUE TITLE
Keep getting 'Layer_Dense' object has no attribute 'weights' with the Lesson 5 python code

### ISSUE THREAD

**Issue by monistan** [Sentdex/NNfSiX#122]
Hi, 

I tried running the code from lesson 5 in various environments, but I keep getting the following error: 'Layer_Dense' object has no attribute 'weights'

I'm pretty new to Python, but this feels like the __init__ part of the Layer_Dense object isn't initialised. Could somebody please explain what is happening here? I'm eager to learn but don't know where to look (outside of this book + yt series + repo off course)

 File "/Documents/PythonProjects/NNFS/lesson5", line 17, in forward
    self.output = np.dot(inputs, self.weights) + self.biases
  File "/Documents/PythonProjects/NNFS/lesson5", line 26, in <module>
    layer1.forward(X)

**Comment by rupeshkmr** [comment]
Hi,
Can you share the screenshot of the File "/Documents/PythonProjects/NNFS/lesson5".
There might be some kind of spell mistakes in the definition of Layer_Dense. Check whether this line is there without any spell mistakes or is not commented out.
`self.weights = 0.1*np.random.randn(n_inputs,n_neurons)`

**Comment by monistan** [comment]
I had _weigths_ instead of _weights_
thanks for the help!

S
