### ISSUE TITLE
python part 8 code error

### ISSUE THREAD

**Issue by gui199** [Sentdex/NNfSiX#158]
The code [p008-Categorical-Cross-Entropy-Loss-applied.py](https://github.com/Sentdex/NNfSiX/blob/master/Python/p008-Categorical-Cross-Entropy-Loss-applied.py)
contain one error in line 54:
`X, y = spiral_data(samples=100, classes=3)`
it should be:
`X, y = spiral_data(points=100, classes=3)`.

**Comment by AliHaider20** [comment]
Submit a PR.

**Comment by gui199** [comment]
ok.
[pull/159](https://github.com/Sentdex/NNfSiX/pull/159)

**Comment by daniel-kukiela** [comment]
@gui199 Looks like you are using a very old NNFS package. You should update it. We have changed that way before we finished the book.

@AliHaider20 There is no issue, Nothing to submit as a PR.
